# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascrip# 
#- script: echo %cd%
# displayName: 'echo'
#- script: 'echo "cicciopasticcio" > C:\Users\Luca\Documents\output.yaml'
#  displayName: 'ciccio'
# name: 'WindowsLocal' 
# version: '3.11.154'
# name: 'Default'
# vmImage: 'ubuntu-latest' 
# - task: oc-cmd@2
#  inputs:
#    version: '3.7'
#    openshiftService: 'My Openshift'
#    cmd: 'oc describe pod/nodejs-ex-3-xtnqn'

trigger:
- master

pool:
  name: 'Default'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      secs=3600   # Set interval (duration) in seconds.
      
      SECONDS=0   # Reset $SECONDS; counting of seconds will (re)start from 0(-ish).
      while (( SECONDS < secs )); do    # Loop until interval has elapsed.
        sleep 5
        if oc get dc -l name='mydeploy' -o name | grep -q ''
        then
          echo 'ciao'
        else
          echo 'errore'
        fi
        echo SECONDS
      done
- task: oc-cmd@2
  inputs:
    openshiftService: 'My Openshift'
    cmd: 'oc new-build nodejs~https://github.com/sclorg/nodejs-ex -l name=mybuild'
    uselocalOc: true
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'oc logs $(oc get bc -l name=''mybuild'' -o name)'
- task: oc-cmd@2
  inputs:
    openshiftService: 'My Openshift'
    uselocalOc: true
    cmd: 'oc new-app nodejs-ex -l name=mydeploy --allow-missing-imagestream-tags'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'oc logs $(oc get dc -l name=''mydeploy'' -o name) --follow=true'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'oc logs $(oc get bc -l name=''mybuild'' -o name)'