# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascrip# 
#- script: echo %cd%
# displayName: 'echo'
#- script: 'echo "cicciopasticcio" > C:\Users\Luca\Documents\output.yaml'
#  displayName: 'ciccio'
# name: 'WindowsLocal' 
# version: '3.11.154'
# name: 'Default'
# vmImage: 'ubuntu-latest' 
# - task: oc-cmd@2
#  inputs:
#    version: '3.7'
#    openshiftService: 'My Openshift'
#    cmd: 'oc describe pod/nodejs-ex-3-xtnqn'

trigger:
- master

pool:
  name: 'Default'

steps:
- task: oc-cmd@2
  inputs:
    openshiftService: 'My Openshift'
    cmd: 'oc describe pod/nodejs-ex-3-xtnqn | grep node | grep kubernetes'
    uselocalOc: true
  