# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascrip# 
#- script: echo %cd%
# displayName: 'echo'
#- script: 'echo "cicciopasticcio" > C:\Users\Luca\Documents\output.yaml'
#  displayName: 'ciccio'
# name: 'WindowsLocal' 
# version: '3.11.154'
# name: 'Default'
# vmImage: 'ubuntu-latest' 
# - task: oc-cmd@2
#  inputs:
#    version: '3.7'
#    openshiftService: 'My Openshift'
#    cmd: 'oc describe pod/nodejs-ex-3-xtnqn'

trigger:
- master

pool:
  name: 'Default'

steps:
- task: oc-cmd@2
  inputs:
    connectionType: 'Runtime Configuration'
    configurationType: 'inline'
    inlineConfig: |
      apiVersion: v1
      clusters:
      - cluster:
          insecure-skip-tls-verify: true
          server: https://api.crc.testing:6443
        name: api-crc-testing:6443
      contexts:
      - context:
          cluster: api-crc-testing:6443
          user: developer/api-crc-testing:6443
        name: /api-crc-testing:6443/developer
      - context:
          cluster: api-crc-testing:6443
          user: system:serviceaccount:hello-openshift:robot/api-crc-testing:6443
        name: /api-crc-testing:6443/system:serviceaccount:hello-openshift:robot
      - context:
          cluster: api-crc-testing:6443
          namespace: default
          user: kube:admin/api-crc-testing:6443
        name: default/api-crc-testing:6443/kube:admin
      - context:
          cluster: api-crc-testing:6443
          namespace: demo-tekton
          user: kube:admin/api-crc-testing:6443
        name: demo-tekton/api-crc-testing:6443/kube:admin
      - context:
          cluster: api-crc-testing:6443
          namespace: pipeline-test
          user: kube:admin/api-crc-testing:6443
        name: pipeline-test/api-crc-testing:6443/kube:admin
      - context:
          cluster: api-crc-testing:6443
          namespace: hello-openshift
          user: kube:admin/api-crc-testing:6443
        name: hello-openshift/api-crc-testing:6443/kube:admin
      current-context: pipeline-test/api-crc-testing:6443/kube:admin
      kind: Config
      preferences: {}
      users:
      - name: developer/api-crc-testing:6443
        user:
          token: HoxJmwr2rwoG9EVz9y01cSqyePvyHTRqu1vuPLKCOC4
      - name: kube:admin/api-crc-testing:6443
        user:
          token: XoFJFq3FbpI20lfZKUucpSenlSWkum-QIv8TW2buuuk
    version: '3.9.103'
    cmd: 'get pods'
