# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascrip# 
#- script: echo %cd%
# displayName: 'echo'
#- script: 'echo "cicciopasticcio" > C:\Users\Luca\Documents\output.yaml'
#  displayName: 'ciccio'
# name: 'WindowsLocal' 
# version: '3.11.154'
# name: 'Default'
# vmImage: 'ubuntu-latest' 
# - task: oc-cmd@2
#  inputs:
#    version: '3.7'
#    openshiftService: 'My Openshift'
#    cmd: 'oc describe pod/nodejs-ex-3-xtnqn'

trigger:
- master

pool:
  name: 'Default' 

steps:
- task: oc-cmd@2
  inputs:
    connectionType: 'Runtime Configuration'
    configurationPath: '/home/luca/Documents/testconfig'
    version: '4.1'
    cmd: 'version'
- task: oc-cmd@2
  inputs:
    connectionType: 'Runtime Configuration'
    configurationPath: '/home/luca/Documents/testconfig'
    version: '3.7'
    cmd: 'oc version'
- task: oc-cmd@2
  inputs:
    connectionType: 'Runtime Configuration'
    configurationPath: '/home/luca/Documents/testconfig'
    version: '3.7'
    cmd: 'oc describe $(oc get pod app-deploy-run-w97zr-taskmame-gszfb-pod-pwjwf -o name)'
- task: oc-cmd@2
  inputs:
    connectionType: 'Runtime Configuration'
    configurationPath: '/home/luca/Documents/testconfig'
    cmd: 'version'
- task: oc-cmd@2
  inputs:
    connectionType: 'Runtime Configuration'
    configurationPath: '/home/luca/Documents/testconfig'
    version: '4.1.6'
    cmd: 'version'

    