# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascrip# 
#- script: echo %cd%
# displayName: 'echo'
#- script: 'echo "cicciopasticcio" > C:\Users\Luca\Documents\output.yaml'
#  displayName: 'ciccio'
# name: 'WindowsLocal' 
# version: '3.11.154'
# name: 'Default'
# vmImage: 'ubuntu-latest' 
# - task: oc-cmd@2
#  inputs:
#    version: '3.7'
#    openshiftService: 'My Openshift'
#    cmd: 'oc describe pod/nodejs-ex-3-xtnqn'

trigger:
- master

pool:
  name: 'Default' 

steps:
- task: OcConditionalCmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'CRC'
    version: '3.9.103'
    cmd: 'get pods'
    condition: 'not_exists'
    resource: 'pod spring-petclinic-1-deploy'

    