# This is a basic workflow to help you get started with Actions

name: CI
on: [push]

env:
  PROJECT: test2
  APP_NAME: myapp

jobs:
  build:
    name: Setup and Deploy
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install oc
      uses: redhat-actions/oc-installer@v1
      with:
        version: '4.3'
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v0.0.1
      with:
        # URL to your OpenShift cluster.
        # Refer to Step 2.
        openshift_server_url: ${{ secrets.CRC_OPENSHIFT_URL }}

        # Authentication Token. Can use username and password instead.
        # Refer to Step 3.
        openshift_token: ${{ secrets.CRC_TOKEN }}

        # Disables SSL cert checking. Use this if you don't have the certificate authority data.
        insecure_skip_tls_verify: true          
    - name: Execute oc commands
      run: |
        oc project ${PROJECT}
        oc new-app ${GITHUB_WORKSPACE} --name ${APP_NAME}
        oc version
        oc expose svc/${{ env.APP_NAME }}

        
