name: CI
on: [push]

jobs:
  build:
   
    runs-on: [self-hosted]

    steps:
    - name: OpenShift Action
      uses: redhat-developer/openshift-actions@v2.0
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        parameters: '{"apitoken": "${{ secrets.API_TOKEN }}", "acceptUntrustedCerts": "true"}'
        cmd: |
          'version'
          'get pods'
        useLocalOc: 'true'
      

