name: CI
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: TestLucaAction
      uses: lstocchi/openshift-actions@1.6.3
      with:
        version: ''
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        parameters: '{"apitoken": "${{ secrets.API_TOKEN }}", "acceptUntrustedCerts": "true"}'
        cmd: |
          'version '
          'get pods'
        proxy: '113.53.230.167:80'

