# This is a basic workflow to help you get started with Actions

name: CI
on: [push]

env:
  PROJECT: test2
  APP_NAME: myapp

jobs:
  build:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: |
        echo '$GITHUB_WORKSPACE'

        
