name: CI
on: [push]

env:
  PROJECT: pods
  IMAGE: hello-python

jobs:
  build:
   
    runs-on: [self-hosted]

    steps:
    - name: OpenShift Action
      uses: redhat-developer/openshift-actions@v2.0
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        parameters: '{"username": "${{ secrets.USERNAME }}", "password": "${{ secrets.PASSWORD }}", "acceptUntrustedCerts": "true"}'
        cmd: |
          'version'
          'get ${PROJECT}'
        useLocalOc: 'true'
      

