name: CI
on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: TestLucaAction
      uses: lstocchi/openshift-actions@1.6.3
      with:
        version: '3.11.96'
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        parameters: '{"apitoken": "${{ secrets.API_TOKEN }}", "acceptUntrustedCerts": "true"}'
        cmd: |
          'version'
          'get pods'
      env:
        https_proxy: "http://7e298c0a.ngrok.io/"
        http_proxy: "http://7e298c0a.ngrok.io/"

