name: CI
on: [push]

jobs:
  build:
   
    runs-on: [self-hosted]

    steps:
    - name: TestLucaAction
      uses: lstocchi/openshift-actions@1.6.9
      with:
        version: '3.11.90'
    - name: scripttest
      run: |
        oc get pods
        oc get pods | grep build
      

