name: CI
on: [push]

jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - name: TestLucaAction
      uses: lstocchi/openshift-actions@1.6.9
      with:
        version: '3.11.30'
    - name: scripttest
      run: |
        oc login --token=${{ secrets.API_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER_URL }}
        oc get pods
        oc get pods | grep build
      

