name: CI
on: [push]

jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - name: TestLucaAction
      uses: lstocchi/openshift-actions@1.6.11
      with:
        version: 'https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz'
    - name: scripttest
      run: |
        oc login --token=${{ secrets.API_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER_URL }}
        oc get pods
        oc get pods | grep build
      

