# This is a basic workflow to help you get started with Actions

name: CI
on: [push]

env:
  PROJECT: tektondemo
  DOCKERIMAGE: node:10
  APPNAME: myapp

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: OpenShift Action
      uses: redhat-developer/openshift-actions@v2.1.0
      with:
        version: '3.11.230'
        openshift_server_url: ${{ secrets.CRC_OPENSHIFT_URL }}
        parameters: '{"apitoken": "${{ secrets.CRC_TOKEN }}", "acceptUntrustedCerts": "true"}'
        cmd: |
          oc project ${PROJECT}
          oc new-build --strategy docker --binary --docker-image ${DOCKERIMAGE} --name ${APPNAME}
          oc start-build ${APPNAME} --from-dir . --follow
          oc new-app ${PROJECT}/${APPNAME}:latest
          oc expose svc/"${APPNAME}"

        
