name: CI
on: [push]

jobs:
  build:
   
    runs-on: [self-hosted]

    steps:
    - name: TestLucaAction
      uses: lstocchi/openshift-actions@1.6.7
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        parameters: '{"apitoken": "${{ secrets.API_TOKEN }}", "acceptUntrustedCerts": "true"}'
        cmd: |
          'version'
          'get ${PROJECT}'
        version: '4.4'
      

